"""
AI Content Publisher
Generate unique professional articles about AI/GenAI and publish them to GitHub.
Credentials are prompted interactively if not found in .env.
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

from generator import ContentGenerator
from publisher import GitHubPublisher

# Post log
HISTORY_FILE = Path(__file__).parent / "published.json"


def load_history() -> list:
    """Load publishing history."""
    if HISTORY_FILE.exists():
        with open(HISTORY_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


def save_history(entry: dict):
    """Save a publishing record."""
    history = load_history()
    history.append(entry)
    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)


def prompt_input(label: str, secret: bool = False) -> str:
    """Prompt user for input, masking if secret."""
    if secret:
        try:
            import getpass
            value = getpass.getpass(f"  {label}: ")
        except Exception:
            value = input(f"  {label}: ")
    else:
        value = input(f"  {label}: ")
    return value.strip()


def get_credentials():
    """Get credentials from .env or prompt interactively."""
    load_dotenv()

    token = os.getenv("GITHUB_TOKEN", "")
    username = os.getenv("GITHUB_USERNAME", "")
    repo = os.getenv("GITHUB_REPO", "")

    if not token:
        print("\n🔑 GitHub Personal Access Token required.")
        print("   Get one: https://github.com/settings/tokens")
        print("   Required scope: 'repo' (Full control of private repositories)\n")
        token = prompt_input("Enter your GitHub token", secret=True)

    if not username:
        username = prompt_input("Enter your GitHub username")

    if not repo:
        repo = prompt_input("Enter your GitHub repository name")

    return token, username, repo


def publish_post(style: str = None, topic: str = None):
    """Generate unique content and publish to GitHub."""
    print("\n" + "=" * 60)
    print("📝 GENERATING UNIQUE CONTENT")
    print("=" * 60)

    # Generate content
    gen = ContentGenerator()
    post = gen.generate_post(style=style, topic_str=topic)

    print(f"📌 Topic:  {post['title']}")
    print(f"🎯 Style:  {post['style']}")
    print(f"{'=' * 60}")
    print(f"\n📝 PREVIEW:\n")
    print(post["full_text"])
    print(f"\n{' '.join(post['hashtags'])}")
    print(f"{'=' * 60}")

    # Save content to a markdown file
    timestamp = datetime.now().strftime("%Y%m%d")
    safe_title = post["title"].lower().replace(" ", "-").replace("(", "").replace(")", "")
    filename = f"{safe_title}.md"
    file_path = Path(filename)

    full_content = f"""# {post['title']}

## Overview

{post['full_text']}

## Tags

{' '.join(post['hashtags'])}

---

*Generated by AI Content Publisher on {datetime.now().strftime("%B %d, %Y")}*
"""

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(full_content)

    print(f"\n💾 Content saved to: {file_path}")

    # Get credentials
    print(f"\n{'=' * 60}")
    print("🔑 AUTHENTICATION")
    print("=" * 60)
    token, username, repo = get_credentials()

    # Publish to GitHub
    print(f"\n{'=' * 60}")
    print(f"🚀 PUBLISHING TO GITHUB")
    print(f"{'=' * 60}")
    print(f"📂 Repository: {username}/{repo}")
    print(f"📄 File: {filename}\n")

    publisher = GitHubPublisher(
        token=token,
        username=username,
        repo_name=repo
    )

    publisher.setup_repo()

    commit_msg = f"Add article: {post['title']}"
    success = publisher.publish_file(str(file_path), commit_msg)

    # Cleanup local repo
    publisher.cleanup()

    # Remove temp file
    if file_path.exists():
        file_path.unlink()

    # Log result
    entry = {
        "published_at": datetime.now().isoformat(),
        "title": post["title"],
        "style": post["style"],
        "filename": filename,
        "repo": f"{username}/{repo}",
        "success": success,
    }
    save_history(entry)

    if success:
        print(f"\n✅ POST PUBLISHED SUCCESSFULLY!")
        print(f"📊 Total posts: {len(load_history())}")
    else:
        print(f"\n❌ Publishing failed.")

    print(f"{'=' * 60}")


def show_history():
    """Show publishing history."""
    history = load_history()
    if not history:
        print("📭 No posts published yet. Run: python main.py publish")
        return

    print(f"\n📜 PUBLISHING HISTORY (last 10):\n")
    for entry in reversed(history[-10:]):
        status = "✅" if entry.get("success") else "❌"
        repo = entry.get("repo", "?")
        print(f"  {status} {entry['published_at'][:10]} | {entry['style']:12s} | {entry['title'][:40]} | {repo}")
    print(f"\n📊 Total posts: {len(history)}\n")


def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="AI Content Publisher — Generate & publish to GitHub",
        epilog="""
Examples:
  python main.py publish                       Generate & publish (random topic)
  python main.py publish --style educational   Specific style
  python main.py publish --topic "RAG"         Specific topic
  python main.py history                       View publish history
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument("command", choices=["publish", "history"], help="Action")
    parser.add_argument("--style", choices=["educational", "trends", "practical"],
                        help="Content style")
    parser.add_argument("--topic", help="Specific topic keyword")

    args = parser.parse_args()

    if args.command == "publish":
        publish_post(style=args.style, topic=args.topic)
    elif args.command == "history":
        show_history()


if __name__ == "__main__":
    main()
